// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtfolkqwcqjotzcgdjov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0Zm9sa3F3Y3Fqb3R6Y2dkam92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjUzODQsImV4cCI6MjA1ODQwMTM4NH0.82-v9A2H2eiRhnTvDD7yQOCLeFgpjxCjWpDK6_zr4EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);